name: Build test

on:
  push:
    branches:
    - nebular
  pull_request:
    branches:
    - nebular

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: "install dependencies"
      run: |
        sudo apt-get update
        sudo apt-get install libgsl-dev
        cp artisoptions_example.h artisoptions.h
    - name: "diagnostic info"
      run: |
        git status
        which cc
        cc --version
    - name: "compile sn3d and exspec"
      run: make sn3d exspec
    - name: "compile sn3d with OpenMP"
      run: make sn3dopenmp
    - name: "compile sn3d with MPI"
      run: |
        sudo apt-get install libopenmpi-dev
        make sn3dmpi
