name: Build test

on:
  push:
    branches:
    - nebular
  pull_request:
    branches:
    - nebular

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: "install dependencies"
      run: |
        sudo apt-get install libgsl-dev
        sudo apt-get install libopenmpi-dev
        cp artisoptions_example.h artisoptions.h
    - name: "diagnostic info"
      run: |
        git status
        which cc
        cc --version
    - name: "compile"
      run: make sn3d exspec
    - name: "compile MPI version"
      run: make sn3dmpi
    - name: "compile OpenMP version"
      run: make sn3dopenmp
