name: C/C++ CI

on:
  push:
    branches:
    - nebular
  pull_request:
    branches:
    - nebular

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: makesn3d
      run: |
        cp artisoptions_example.h artisoptions.h
        sudo apt-get install libgsl-dev
        git status
        make sn3d
