name: Continuous integration

on:
  push:
    branches:
    - nebular
  pull_request:
    branches:
    - nebular

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v2.3.4

    - name: "install dependencies"
      run: |
        # sudo apt-get update
        sudo apt-get install libgsl-dev
        # sudo apt-get install clang
        cp artisoptions_example.h artisoptions.h

    - name: "diagnostic info"
      run: |
        git status
        which gcc
        gcc --version
        which clang++
        clang++ --version
        export CC=clang
        export CXX=clang++

    - name: "compile with gcc"
      run: make CXX=g++ sn3d exspec

    - name: "compile with clang"
      run: make CXX=clang++ sn3d exspec

    - name: "compile"
      run: make

    # - name: "compile sn3d with OpenMP"
    #   run: make sn3dopenmp

    # - name: "compile sn3d with MPI"
    #   run: |
    #     sudo apt-get install libopenmpi-dev
    #     make sn3dmpi

    - name: "Setup test nebularonezone"
      run: |
        cp tests/nebularonezone/artisoptions.h .
        make TESTMODE=ON sn3d exspec
        cp sn3d tests/nebularonezone/
        cp exspec tests/nebularonezone/

    # we can cache this, but then we don't test the code that generates ratecoeff.dat
    # - name: Cache ratecoeff.dat
    #   uses: actions/cache@v2.1.4
    #   with:
    #     path: "tests/nebularonezone/ratecoeff.dat"
    #     key: "tests/nebularonezone/ratecoeff.dat"

    - name: "Run test nebularonezone test"
      run: |
        cd tests/nebularonezone/
        gunzip -v *.gz
        cp input-newrun.txt input.txt
        touch output_0-0.txt
        ./sn3d
        cat output_0-0.txt
        cat estimators_0000.out
        ./exspec
        cat exspec.txt
        mkdir output
        cp output_0-0.txt exspec.txt *.out output/

    # - name: Upload output files
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: test-nebularonezone-output
    #     path: tests/nebularonezone/output